"""硅基流动上适合本 Agent（工具调用 + 代码分析）的模型目录。

价格为控制台常见标价（元 / 百万 tokens），会变动；以
https://www.siliconflow.cn/pricing 为准。
"""

from __future__ import annotations

from typing import Any, Dict, List

# 本 Agent 常用参数（与默认配置一致）
AGENT_DEFAULTS = {
    "max_steps": 8,
    "max_tokens_tool": 1024,
    "max_tokens_report": 4096,
    "enable_thinking": False,
    "temperature": None,
    "tool_choice_first_step": "required",
}

MODELS: List[Dict[str, Any]] = [
    {
        "id": "Qwen/Qwen3-8B",
        "tier": "free",
        "role": "default",
        "label": "默认 · 免费练手",
        "context": "131K",
        "tools": True,
        "input_cny_per_m": 0,
        "output_cny_per_m": 0,
        "value": "high",
        "note": "免费档主力。工具调用稳，适合本项目。报告质量中等，延迟受平台排队影响。",
    },
    {
        "id": "Qwen/Qwen2.5-7B-Instruct",
        "tier": "free",
        "role": "backup",
        "label": "备选 · 指令更稳",
        "context": "32K–128K",
        "tools": True,
        "input_cny_per_m": 0,
        "output_cny_per_m": 0,
        "value": "high",
        "note": "官方 function calling 名单。比 Qwen3-8B 更少 thinking 干扰。",
    },
    {
        "id": "THUDM/GLM-4-9B-0414",
        "tier": "free",
        "role": "backup",
        "label": "备选 · 智谱 9B",
        "context": "32K",
        "tools": True,
        "input_cny_per_m": 0,
        "output_cny_per_m": 0,
        "value": "medium",
        "note": "免费 FC。中文说明尚可，复杂仓库容易漏。",
    },
    {
        "id": "Qwen/Qwen3.5-4B",
        "tier": "free",
        "role": "light",
        "label": "轻量 · 更快更弱",
        "context": "32K+",
        "tools": True,
        "input_cny_per_m": 0,
        "output_cny_per_m": 0,
        "value": "medium",
        "note": "更便宜更快，多步 JSON 报告容易不完整。",
    },
    {
        "id": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
        "tier": "paid",
        "role": "code",
        "label": "代码专项 · 性价比高",
        "context": "160K–262K",
        "tools": True,
        "input_cny_per_m": 0.5,
        "output_cny_per_m": 2.0,
        "value": "high",
        "note": "代码/Agent 首选付费档。工具调用 + 读源码比 7–9B 明显稳，价格低于满血 V3/R1。",
    },
    {
        "id": "Qwen/Qwen3-32B",
        "tier": "paid",
        "role": "quality",
        "label": "质量提升",
        "context": "131K",
        "tools": True,
        "input_cny_per_m": 1.0,
        "output_cny_per_m": 4.0,
        "value": "high",
        "note": "通用分析质量好。须 enable_thinking=false，否则 tool 循环变慢。",
    },
    {
        "id": "Qwen/Qwen3-14B",
        "tier": "paid",
        "role": "quality",
        "label": "中档质量",
        "context": "131K",
        "tools": True,
        "input_cny_per_m": 0.5,
        "output_cny_per_m": 2.0,
        "value": "high",
        "note": "介于 8B 与 32B 之间，付费不高。",
    },
    {
        "id": "deepseek-ai/DeepSeek-V3",
        "tier": "paid",
        "role": "quality",
        "label": "通用强模型",
        "context": "64K–164K",
        "tools": True,
        "input_cny_per_m": 2.0,
        "output_cny_per_m": 8.0,
        "value": "medium",
        "note": "报告质量高，比 R1 便宜。多步 Agent 费用约为免费档的数倍。",
    },
    {
        "id": "deepseek-ai/DeepSeek-V3.2",
        "tier": "paid",
        "role": "quality",
        "label": "V3 新版",
        "context": "164K",
        "tools": True,
        "input_cny_per_m": 4.0,
        "output_cny_per_m": 6.0,
        "value": "medium",
        "note": "比 V3 新。缓存命中可降输入成本。",
    },
    {
        "id": "deepseek-ai/DeepSeek-V4-Flash",
        "tier": "paid",
        "role": "speed",
        "label": "新旗舰 · 偏快",
        "context": "1M",
        "tools": True,
        "input_cny_per_m": 1.5,
        "output_cny_per_m": 4.5,
        "value": "high",
        "note": "长上下文、工具调用。分时段计价，低峰更便宜。适合大仓。",
    },
    {
        "id": "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        "tier": "paid",
        "role": "flagship",
        "label": "代码旗舰",
        "context": "262K",
        "tools": True,
        "input_cny_per_m": 2.0,
        "output_cny_per_m": 8.0,
        "value": "medium",
        "note": "代码能力最强之一，贵且慢。只建议难仓/修复杂 Bug。",
    },
    {
        "id": "deepseek-ai/DeepSeek-R1",
        "tier": "paid",
        "role": "flagship",
        "label": "推理旗舰",
        "context": "164K",
        "tools": True,
        "input_cny_per_m": 4.0,
        "output_cny_per_m": 16.0,
        "value": "low",
        "note": "思考链吃步数和输出 token，本 Agent 默认不推荐（贵、慢）。",
    },
]


def catalog_payload() -> Dict[str, Any]:
    return {
        "defaults": AGENT_DEFAULTS,
        "models": MODELS,
        "price_unit": "CNY per 1M tokens",
        "disclaimer": "价格来自硅基流动公开标价，可能随时调整；免费档有 RPM/TPM 上限。",
    }
